

const CURRENCIES = [
  ["AED","ae"],
  ["AFN","af"],
  ["ALL","al"],
  ["AMD","am"],
  ["ANG","cw"],
  ["AOA","ao"],
  ["ARS","ar"],
  ["AUD","au"],
  ["AWG","aw"],
  ["AZN","az"],
  ["BAM","ba"],
  ["BBD","bb"],
  ["BDT","bd"],
  ["BGN","bg"],
  ["BHD","bh"],
  ["BIF","bi"],
  ["BMD","bm"],
  ["BND","bn"],
  ["BOB","bo"],
  ["BRL","br"],
  ["BSD","bs"],
  ["BTN","bt"],
  ["BWP","bw"],
  ["BYN","by"],
  ["BZD","bz"],
  ["CAD","ca"],
  ["CDF","cd"],
  ["CHF","ch"],
  ["CLP","cl"],
  ["CNY","cn"],
  ["COP","co"],
  ["CRC","cr"],
  ["CUP","cu"],
  ["CVE","cv"],
  ["CZK","cz"],
  ["DJF","dj"],
  ["DKK","dk"],
  ["DOP","do"],
  ["DZD","dz"],
  ["EGP","eg"],
  ["ERN","er"],
  ["ETB","et"],
  ["EUR","eu"],
  ["FJD","fj"],
  ["FKP","fk"],
  ["GBP","gb"],
  ["GEL","ge"],
  ["GHS","gh"],
  ["GIP","gi"],
  ["GMD","gm"],
  ["GNF","gn"],
  ["GTQ","gt"],
  ["GYD","gy"],
  ["HKD","hk"],
  ["HNL","hn"],
  ["HRK","hr"],
  ["HTG","ht"],
  ["HUF","hu"],
  ["IDR","id"],
  ["ILS","il"],
  ["INR","in"],
  ["IQD","iq"],
  ["IRR","ir"],
  ["ISK","is"],
  ["JMD","jm"],
  ["JOD","jo"],
  ["JPY","jp"],
  ["KES","ke"],
  ["KGS","kg"],
  ["KHR","kh"],
  ["KMF","km"],
  ["KRW","kr"],
  ["KWD","kw"],
  ["KYD","ky"],
  ["KZT","kz"],
  ["LAK","la"],
  ["LBP","lb"],
  ["LKR","lk"],
  ["LRD","lr"],
  ["LSL","ls"],
  ["LYD","ly"],
  ["MAD","ma"],
  ["MDL","md"],
  ["MGA","mg"],
  ["MKD","mk"],
  ["MMK","mm"],
  ["MNT","mn"],
  ["MOP","mo"],
  ["MRU","mr"],
  ["MUR","mu"],
  ["MVR","mv"],
  ["MWK","mw"],
  ["MXN","mx"],
  ["MYR","my"],
  ["MZN","mz"],
  ["NAD","na"],
  ["NGN","ng"],
  ["NIO","ni"],
  ["NOK","no"],
  ["NPR","np"],
  ["NZD","nz"],
  ["OMR","om"],
  ["PAB","pa"],
  ["PEN","pe"],
  ["PGK","pg"],
  ["PHP","ph"],
  ["PKR","pk"],
  ["PLN","pl"],
  ["PYG","py"],
  ["QAR","qa"],
  ["RON","ro"],
  ["RSD","rs"],
  ["RUB","ru"],
  ["RWF","rw"],
  ["SAR","sa"],
  ["SBD","sb"],
  ["SCR","sc"],
  ["SDG","sd"],
  ["SEK","se"],
  ["SGD","sg"],
  ["SHP","sh"],
  ["SLL","sl"],
  ["SOS","so"],
  ["SRD","sr"],
  ["SSP","ss"],
  ["STN","st"],
  ["SVC","sv"],
  ["SYP","sy"],
  ["SZL","sz"],
  ["THB","th"],
  ["TJS","tj"],
  ["TMT","tm"],
  ["TND","tn"],
  ["TOP","to"],
  ["TRY","tr"],
  ["TTD","tt"],
  ["TWD","tw"],
  ["TZS","tz"],
  ["UAH","ua"],
  ["UGX","ug"],
  ["USD","us"],
  ["UYU","uy"],
  ["UZS","uz"],
  ["VES","ve"],
  ["VND","vn"],
  ["VUV","vu"],
  ["WST","ws"],
  ["XAF","cm"],
  ["XCD","ag"],
  ["XOF","sn"],
  ["XPF","pf"],
  ["YER","ye"],
  ["ZAR","za"],
  ["ZMW","zm"],
  ["ZWL","zw"]
];

const NAMES = {
  en: {"AED":"United Arab Emirates","AFN":"Afghanistan","ALL":"Albania","AMD":"Armenia","ANG":"Curaçao","AOA":"Angola","ARS":"Argentina","AUD":"Australia","AWG":"Aruba","AZN":"Azerbaijan","BAM":"Bosnia & Herzegovina","BBD":"Barbados","BDT":"Bangladesh","BGN":"Bulgaria","BHD":"Bahrain","BIF":"Burundi","BMD":"Bermuda","BND":"Brunei","BOB":"Bolivia","BRL":"Brazil","BSD":"Bahamas","BTN":"Bhutan","BWP":"Botswana","BYN":"Belarus","BZD":"Belize","CAD":"Canada","CDF":"Congo - Kinshasa","CHF":"Switzerland","CLP":"Chile","CNY":"China","COP":"Colombia","CRC":"Costa Rica","CUP":"Cuba","CVE":"Cape Verde","CZK":"Czechia","DJF":"Djibouti","DKK":"Denmark","DOP":"Dominican Republic","DZD":"Algeria","EGP":"Egypt","ERN":"Eritrea","ETB":"Ethiopia","EUR":"European Union","FJD":"Fiji","FKP":"Falkland Islands","GBP":"United Kingdom","GEL":"Georgia","GHS":"Ghana","GIP":"Gibraltar","GMD":"Gambia","GNF":"Guinea","GTQ":"Guatemala","GYD":"Guyana","HKD":"Hong Kong SAR China","HNL":"Honduras","HRK":"Croatia","HTG":"Haiti","HUF":"Hungary","IDR":"Indonesia","ILS":"Israel","INR":"India","IQD":"Iraq","IRR":"Iran","ISK":"Iceland","JMD":"Jamaica","JOD":"Jordan","JPY":"Japan","KES":"Kenya","KGS":"Kyrgyzstan","KHR":"Cambodia","KMF":"Comoros","KRW":"South Korea","KWD":"Kuwait","KYD":"Cayman Islands","KZT":"Kazakhstan","LAK":"Laos","LBP":"Lebanon","LKR":"Sri Lanka","LRD":"Liberia","LSL":"Lesotho","LYD":"Libya","MAD":"Morocco","MDL":"Moldova","MGA":"Madagascar","MKD":"North Macedonia","MMK":"Myanmar (Burma)","MNT":"Mongolia","MOP":"Macao SAR China","MRU":"Mauritania","MUR":"Mauritius","MVR":"Maldives","MWK":"Malawi","MXN":"Mexico","MYR":"Malaysia","MZN":"Mozambique","NAD":"Namibia","NGN":"Nigeria","NIO":"Nicaragua","NOK":"Norway","NPR":"Nepal","NZD":"New Zealand","OMR":"Oman","PAB":"Panama","PEN":"Peru","PGK":"Papua New Guinea","PHP":"Philippines","PKR":"Pakistan","PLN":"Poland","PYG":"Paraguay","QAR":"Qatar","RON":"Romania","RSD":"Serbia","RUB":"Russia","RWF":"Rwanda","SAR":"Saudi Arabia","SBD":"Solomon Islands","SCR":"Seychelles","SDG":"Sudan","SEK":"Sweden","SGD":"Singapore","SHP":"St. Helena","SLL":"Sierra Leone","SOS":"Somalia","SRD":"Suriname","SSP":"South Sudan","STN":"São Tomé & Príncipe","SVC":"El Salvador","SYP":"Syria","SZL":"Eswatini","THB":"Thailand","TJS":"Tajikistan","TMT":"Turkmenistan","TND":"Tunisia","TOP":"Tonga","TRY":"Türkiye","TTD":"Trinidad & Tobago","TWD":"Taiwan","TZS":"Tanzania","UAH":"Ukraine","UGX":"Uganda","USD":"United States","UYU":"Uruguay","UZS":"Uzbekistan","VES":"Venezuela","VND":"Vietnam","VUV":"Vanuatu","WST":"Samoa","XAF":"Cameroon","XCD":"Antigua & Barbuda","XOF":"Senegal","XPF":"French Polynesia","YER":"Yemen","ZAR":"South Africa","ZMW":"Zambia","ZWL":"Zimbabwe"},
  he: {"AED":"איחוד האמירויות הערביות","AFN":"אפגניסטן","ALL":"אלבניה","AMD":"ארמניה","ANG":"קוראסאו","AOA":"אנגולה","ARS":"ארגנטינה","AUD":"אוסטרליה","AWG":"ארובה","AZN":"אזרבייג׳ן","BAM":"בוסניה והרצגובינה","BBD":"ברבדוס","BDT":"בנגלדש","BGN":"בולגריה","BHD":"בחריין","BIF":"בורונדי","BMD":"ברמודה","BND":"ברוניי","BOB":"בוליביה","BRL":"ברזיל","BSD":"איי בהאמה","BTN":"בהוטן","BWP":"בוטסואנה","BYN":"בלארוס","BZD":"בליז","CAD":"קנדה","CDF":"קונגו - קינשאסה","CHF":"שווייץ","CLP":"צ׳ילה","CNY":"סין","COP":"קולומביה","CRC":"קוסטה ריקה","CUP":"קובה","CVE":"כף ורדה","CZK":"צ׳כיה","DJF":"ג׳יבוטי","DKK":"דנמרק","DOP":"הרפובליקה הדומיניקנית","DZD":"אלג׳יריה","EGP":"מצרים","ERN":"אריתריאה","ETB":"אתיופיה","EUR":"האיחוד האירופי","FJD":"פיג׳י","FKP":"איי פוקלנד","GBP":"בריטניה","GEL":"גאורגיה","GHS":"גאנה","GIP":"גיברלטר","GMD":"גמביה","GNF":"גינאה","GTQ":"גואטמלה","GYD":"גיאנה","HKD":"הונג קונג (אזור מנהלי מיוחד של סין)","HNL":"הונדורס","HRK":"קרואטיה","HTG":"האיטי","HUF":"הונגריה","IDR":"אינדונזיה","ILS":"ישראל","INR":"הודו","IQD":"עיראק","IRR":"איראן","ISK":"איסלנד","JMD":"ג׳מייקה","JOD":"ירדן","JPY":"יפן","KES":"קניה","KGS":"קירגיזסטן","KHR":"קמבודיה","KMF":"קומורו","KRW":"קוריאה הדרומית","KWD":"כווית","KYD":"איי קיימן","KZT":"קזחסטן","LAK":"לאוס","LBP":"לבנון","LKR":"סרי לנקה","LRD":"ליבריה","LSL":"לסוטו","LYD":"לוב","MAD":"מרוקו","MDL":"מולדובה","MGA":"מדגסקר","MKD":"מקדוניה הצפונית","MMK":"מיאנמר (בורמה)","MNT":"מונגוליה","MOP":"מקאו (אזור מנהלי מיוחד של סין)","MRU":"מאוריטניה","MUR":"מאוריציוס","MVR":"האיים המלדיביים","MWK":"מלאווי","MXN":"מקסיקו","MYR":"מלזיה","MZN":"מוזמביק","NAD":"נמיביה","NGN":"ניגריה","NIO":"ניקרגואה","NOK":"נורווגיה","NPR":"נפאל","NZD":"ניו זילנד","OMR":"עומאן","PAB":"פנמה","PEN":"פרו","PGK":"פפואה גינאה החדשה","PHP":"הפיליפינים","PKR":"פקיסטן","PLN":"פולין","PYG":"פרגוואי","QAR":"קטאר","RON":"רומניה","RSD":"סרביה","RUB":"רוסיה","RWF":"רואנדה","SAR":"ערב הסעודית","SBD":"איי שלמה","SCR":"איי סיישל","SDG":"סודן","SEK":"שוודיה","SGD":"סינגפור","SHP":"סנט הלנה","SLL":"סיירה לאון","SOS":"סומליה","SRD":"סורינאם","SSP":"דרום סודן","STN":"סאו טומה ופרינסיפה","SVC":"אל סלבדור","SYP":"סוריה","SZL":"אסוואטיני","THB":"תאילנד","TJS":"טג׳יקיסטן","TMT":"טורקמניסטן","TND":"תוניסיה","TOP":"טונגה","TRY":"טורקיה","TTD":"טרינידד וטובגו","TWD":"טייוואן","TZS":"טנזניה","UAH":"אוקראינה","UGX":"אוגנדה","USD":"ארצות הברית","UYU":"אורוגוואי","UZS":"אוזבקיסטן","VES":"ונצואלה","VND":"וייטנאם","VUV":"ונואטו","WST":"סמואה","XAF":"קמרון","XCD":"אנטיגואה וברבודה","XOF":"סנגל","XPF":"פולינזיה הצרפתית","YER":"תימן","ZAR":"דרום אפריקה","ZMW":"זמביה","ZWL":"זימבבואה"},
  ru: {"AED":"ОАЭ","AFN":"Афганистан","ALL":"Албания","AMD":"Армения","ANG":"Кюрасао","AOA":"Ангола","ARS":"Аргентина","AUD":"Австралия","AWG":"Аруба","AZN":"Азербайджан","BAM":"Босния и Герцеговина","BBD":"Барбадос","BDT":"Бангладеш","BGN":"Болгария","BHD":"Бахрейн","BIF":"Бурунди","BMD":"Бермудские о-ва","BND":"Бруней","BOB":"Боливия","BRL":"Бразилия","BSD":"Багамы","BTN":"Бутан","BWP":"Ботсвана","BYN":"Беларусь","BZD":"Белиз","CAD":"Канада","CDF":"Конго - Киншаса","CHF":"Швейцария","CLP":"Чили","CNY":"Китай","COP":"Колумбия","CRC":"Коста-Рика","CUP":"Куба","CVE":"Кабо-Верде","CZK":"Чехия","DJF":"Джибути","DKK":"Дания","DOP":"Доминиканская Республика","DZD":"Алжир","EGP":"Египет","ERN":"Эритрея","ETB":"Эфиопия","EUR":"Европейский союз","FJD":"Фиджи","FKP":"Фолклендские о-ва","GBP":"Великобритания","GEL":"Грузия","GHS":"Гана","GIP":"Гибралтар","GMD":"Гамбия","GNF":"Гвинея","GTQ":"Гватемала","GYD":"Гайана","HKD":"Гонконг (САР)","HNL":"Гондурас","HRK":"Хорватия","HTG":"Гаити","HUF":"Венгрия","IDR":"Индонезия","ILS":"Израиль","INR":"Индия","IQD":"Ирак","IRR":"Иран","ISK":"Исландия","JMD":"Ямайка","JOD":"Иордания","JPY":"Япония","KES":"Кения","KGS":"Киргизия","KHR":"Камбоджа","KMF":"Коморы","KRW":"Республика Корея","KWD":"Кувейт","KYD":"о-ва Кайман","KZT":"Казахстан","LAK":"Лаос","LBP":"Ливан","LKR":"Шри-Ланка","LRD":"Либерия","LSL":"Лесото","LYD":"Ливия","MAD":"Марокко","MDL":"Молдова","MGA":"Мадагаскар","MKD":"Северная Македония","MMK":"Мьянма (Бирма)","MNT":"Монголия","MOP":"Макао (САР)","MRU":"Мавритания","MUR":"Маврикий","MVR":"Мальдивы","MWK":"Малави","MXN":"Мексика","MYR":"Малайзия","MZN":"Мозамбик","NAD":"Намибия","NGN":"Нигерия","NIO":"Никарагуа","NOK":"Норвегия","NPR":"Непал","NZD":"Новая Зеландия","OMR":"Оман","PAB":"Панама","PEN":"Перу","PGK":"Папуа - Новая Гвинея","PHP":"Филиппины","PKR":"Пакистан","PLN":"Польша","PYG":"Парагвай","QAR":"Катар","RON":"Румыния","RSD":"Сербия","RUB":"Россия","RWF":"Руанда","SAR":"Саудовская Аравия","SBD":"Соломоновы о-ва","SCR":"Сейшельские о-ва","SDG":"Судан","SEK":"Швеция","SGD":"Сингапур","SHP":"о-в Св. Елены","SLL":"Сьерра-Леоне","SOS":"Сомали","SRD":"Суринам","SSP":"Южный Судан","STN":"Сан-Томе и Принсипи","SVC":"Сальвадор","SYP":"Сирия","SZL":"Эсватини","THB":"Таиланд","TJS":"Таджикистан","TMT":"Туркменистан","TND":"Тунис","TOP":"Тонга","TRY":"Турция","TTD":"Тринидад и Тобаго","TWD":"Тайвань","TZS":"Танзания","UAH":"Украина","UGX":"Уганда","USD":"Соединенные Штаты","UYU":"Уругвай","UZS":"Узбекистан","VES":"Венесуэла","VND":"Вьетнам","VUV":"Вануату","WST":"Самоа","XAF":"Камерун","XCD":"Антигуа и Барбуда","XOF":"Сенегал","XPF":"Французская Полинезия","YER":"Йемен","ZAR":"Южно-Африканская Республика","ZMW":"Замбия","ZWL":"Зимбабве"},
  es: {"AED":"Emiratos Árabes Unidos","AFN":"Afganistán","ALL":"Albania","AMD":"Armenia","ANG":"Curazao","AOA":"Angola","ARS":"Argentina","AUD":"Australia","AWG":"Aruba","AZN":"Azerbaiyán","BAM":"Bosnia y Herzegovina","BBD":"Barbados","BDT":"Bangladés","BGN":"Bulgaria","BHD":"Baréin","BIF":"Burundi","BMD":"Bermudas","BND":"Brunéi","BOB":"Bolivia","BRL":"Brasil","BSD":"Bahamas","BTN":"Bután","BWP":"Botsuana","BYN":"Bielorrusia","BZD":"Belice","CAD":"Canadá","CDF":"República Democrática del Congo","CHF":"Suiza","CLP":"Chile","CNY":"China","COP":"Colombia","CRC":"Costa Rica","CUP":"Cuba","CVE":"Cabo Verde","CZK":"Chequia","DJF":"Yibuti","DKK":"Dinamarca","DOP":"República Dominicana","DZD":"Argelia","EGP":"Egipto","ERN":"Eritrea","ETB":"Etiopía","EUR":"Unión Europea","FJD":"Fiyi","FKP":"Islas Malvinas","GBP":"Reino Unido","GEL":"Georgia","GHS":"Ghana","GIP":"Gibraltar","GMD":"Gambia","GNF":"Guinea","GTQ":"Guatemala","GYD":"Guyana","HKD":"RAE de Hong Kong (China)","HNL":"Honduras","HRK":"Croacia","HTG":"Haití","HUF":"Hungría","IDR":"Indonesia","ILS":"Israel","INR":"India","IQD":"Irak","IRR":"Irán","ISK":"Islandia","JMD":"Jamaica","JOD":"Jordania","JPY":"Japón","KES":"Kenia","KGS":"Kirguistán","KHR":"Camboya","KMF":"Comoras","KRW":"Corea del Sur","KWD":"Kuwait","KYD":"Islas Caimán","KZT":"Kazajistán","LAK":"Laos","LBP":"Líbano","LKR":"Sri Lanka","LRD":"Liberia","LSL":"Lesoto","LYD":"Libia","MAD":"Marruecos","MDL":"Moldavia","MGA":"Madagascar","MKD":"Macedonia del Norte","MMK":"Myanmar (Birmania)","MNT":"Mongolia","MOP":"RAE de Macao (China)","MRU":"Mauritania","MUR":"Mauricio","MVR":"Maldivas","MWK":"Malaui","MXN":"México","MYR":"Malasia","MZN":"Mozambique","NAD":"Namibia","NGN":"Nigeria","NIO":"Nicaragua","NOK":"Noruega","NPR":"Nepal","NZD":"Nueva Zelanda","OMR":"Omán","PAB":"Panamá","PEN":"Perú","PGK":"Papúa Nueva Guinea","PHP":"Filipinas","PKR":"Pakistán","PLN":"Polonia","PYG":"Paraguay","QAR":"Catar","RON":"Rumanía","RSD":"Serbia","RUB":"Rusia","RWF":"Ruanda","SAR":"Arabia Saudí","SBD":"Islas Salomón","SCR":"Seychelles","SDG":"Sudán","SEK":"Suecia","SGD":"Singapur","SHP":"Santa Elena","SLL":"Sierra Leona","SOS":"Somalia","SRD":"Surinam","SSP":"Sudán del Sur","STN":"Santo Tomé y Príncipe","SVC":"El Salvador","SYP":"Siria","SZL":"Esuatini","THB":"Tailandia","TJS":"Tayikistán","TMT":"Turkmenistán","TND":"Túnez","TOP":"Tonga","TRY":"Turquía","TTD":"Trinidad y Tobago","TWD":"Taiwán","TZS":"Tanzania","UAH":"Ucrania","UGX":"Uganda","USD":"Estados Unidos","UYU":"Uruguay","UZS":"Uzbekistán","VES":"Venezuela","VND":"Vietnam","VUV":"Vanuatu","WST":"Samoa","XAF":"Camerún","XCD":"Antigua y Barbuda","XOF":"Senegal","XPF":"Polinesia Francesa","YER":"Yemen","ZAR":"Sudáfrica","ZMW":"Zambia","ZWL":"Zimbabue"},
  ja: {"AED":"アラブ首長国連邦","AFN":"アフガニスタン","ALL":"アルバニア","AMD":"アルメニア","ANG":"キュラソー","AOA":"アンゴラ","ARS":"アルゼンチン","AUD":"オーストラリア","AWG":"アルバ","AZN":"アゼルバイジャン","BAM":"ボスニア・ヘルツェゴビナ","BBD":"バルバドス","BDT":"バングラデシュ","BGN":"ブルガリア","BHD":"バーレーン","BIF":"ブルンジ","BMD":"バミューダ","BND":"ブルネイ","BOB":"ボリビア","BRL":"ブラジル","BSD":"バハマ","BTN":"ブータン","BWP":"ボツワナ","BYN":"ベラルーシ","BZD":"ベリーズ","CAD":"カナダ","CDF":"コンゴ民主共和国(キンシャサ)","CHF":"スイス","CLP":"チリ","CNY":"中国","COP":"コロンビア","CRC":"コスタリカ","CUP":"キューバ","CVE":"カーボベルデ","CZK":"チェコ","DJF":"ジブチ","DKK":"デンマーク","DOP":"ドミニカ共和国","DZD":"アルジェリア","EGP":"エジプト","ERN":"エリトリア","ETB":"エチオピア","EUR":"欧州連合","FJD":"フィジー","FKP":"フォークランド諸島","GBP":"イギリス","GEL":"ジョージア","GHS":"ガーナ","GIP":"ジブラルタル","GMD":"ガンビア","GNF":"ギニア","GTQ":"グアテマラ","GYD":"ガイアナ","HKD":"中華人民共和国香港特別行政区","HNL":"ホンジュラス","HRK":"クロアチア","HTG":"ハイチ","HUF":"ハンガリー","IDR":"インドネシア","ILS":"イスラエル","INR":"インド","IQD":"イラク","IRR":"イラン","ISK":"アイスランド","JMD":"ジャマイカ","JOD":"ヨルダン","JPY":"日本","KES":"ケニア","KGS":"キルギス","KHR":"カンボジア","KMF":"コモロ","KRW":"韓国","KWD":"クウェート","KYD":"ケイマン諸島","KZT":"カザフスタン","LAK":"ラオス","LBP":"レバノン","LKR":"スリランカ","LRD":"リベリア","LSL":"レソト","LYD":"リビア","MAD":"モロッコ","MDL":"モルドバ","MGA":"マダガスカル","MKD":"北マケドニア","MMK":"ミャンマー (ビルマ)","MNT":"モンゴル","MOP":"中華人民共和国マカオ特別行政区","MRU":"モーリタニア","MUR":"モーリシャス","MVR":"モルディブ","MWK":"マラウイ","MXN":"メキシコ","MYR":"マレーシア","MZN":"モザンビーク","NAD":"ナミビア","NGN":"ナイジェリア","NIO":"ニカラグア","NOK":"ノルウェー","NPR":"ネパール","NZD":"ニュージーランド","OMR":"オマーン","PAB":"パナマ","PEN":"ペルー","PGK":"パプアニューギニア","PHP":"フィリピン","PKR":"パキスタン","PLN":"ポーランド","PYG":"パラグアイ","QAR":"カタール","RON":"ルーマニア","RSD":"セルビア","RUB":"ロシア","RWF":"ルワンダ","SAR":"サウジアラビア","SBD":"ソロモン諸島","SCR":"セーシェル","SDG":"スーダン","SEK":"スウェーデン","SGD":"シンガポール","SHP":"セントヘレナ","SLL":"シエラレオネ","SOS":"ソマリア","SRD":"スリナム","SSP":"南スーダン","STN":"サントメ・プリンシペ","SVC":"エルサルバドル","SYP":"シリア","SZL":"エスワティニ","THB":"タイ","TJS":"タジキスタン","TMT":"トルクメニスタン","TND":"チュニジア","TOP":"トンガ","TRY":"トルコ","TTD":"トリニダード・トバゴ","TWD":"台湾","TZS":"タンザニア","UAH":"ウクライナ","UGX":"ウガンダ","USD":"アメリカ合衆国","UYU":"ウルグアイ","UZS":"ウズベキスタン","VES":"ベネズエラ","VND":"ベトナム","VUV":"バヌアツ","WST":"サモア","XAF":"カメルーン","XCD":"アンティグア・バーブーダ","XOF":"セネガル","XPF":"仏領ポリネシア","YER":"イエメン","ZAR":"南アフリカ","ZMW":"ザンビア","ZWL":"ジンバブエ"},
  zh: {"AED":"阿拉伯联合酋长国","AFN":"阿富汗","ALL":"阿尔巴尼亚","AMD":"亚美尼亚","ANG":"库拉索","AOA":"安哥拉","ARS":"阿根廷","AUD":"澳大利亚","AWG":"阿鲁巴","AZN":"阿塞拜疆","BAM":"波斯尼亚和黑塞哥维那","BBD":"巴巴多斯","BDT":"孟加拉国","BGN":"保加利亚","BHD":"巴林","BIF":"布隆迪","BMD":"百慕大","BND":"文莱","BOB":"玻利维亚","BRL":"巴西","BSD":"巴哈马","BTN":"不丹","BWP":"博茨瓦纳","BYN":"白俄罗斯","BZD":"伯利兹","CAD":"加拿大","CDF":"刚果（金）","CHF":"瑞士","CLP":"智利","CNY":"中国","COP":"哥伦比亚","CRC":"哥斯达黎加","CUP":"古巴","CVE":"佛得角","CZK":"捷克","DJF":"吉布提","DKK":"丹麦","DOP":"多米尼加共和国","DZD":"阿尔及利亚","EGP":"埃及","ERN":"厄立特里亚","ETB":"埃塞俄比亚","EUR":"欧盟","FJD":"斐济","FKP":"福克兰群岛","GBP":"英国","GEL":"格鲁吉亚","GHS":"加纳","GIP":"直布罗陀","GMD":"冈比亚","GNF":"几内亚","GTQ":"危地马拉","GYD":"圭亚那","HKD":"中国香港特别行政区","HNL":"洪都拉斯","HRK":"克罗地亚","HTG":"海地","HUF":"匈牙利","IDR":"印度尼西亚","ILS":"以色列","INR":"印度","IQD":"伊拉克","IRR":"伊朗","ISK":"冰岛","JMD":"牙买加","JOD":"约旦","JPY":"日本","KES":"肯尼亚","KGS":"吉尔吉斯斯坦","KHR":"柬埔寨","KMF":"科摩罗","KRW":"韩国","KWD":"科威特","KYD":"开曼群岛","KZT":"哈萨克斯坦","LAK":"老挝","LBP":"黎巴嫩","LKR":"斯里兰卡","LRD":"利比里亚","LSL":"莱索托","LYD":"利比亚","MAD":"摩洛哥","MDL":"摩尔多瓦","MGA":"马达加斯加","MKD":"北马其顿","MMK":"缅甸","MNT":"蒙古","MOP":"中国澳门特别行政区","MRU":"毛里塔尼亚","MUR":"毛里求斯","MVR":"马尔代夫","MWK":"马拉维","MXN":"墨西哥","MYR":"马来西亚","MZN":"莫桑比克","NAD":"纳米比亚","NGN":"尼日利亚","NIO":"尼加拉瓜","NOK":"挪威","NPR":"尼泊尔","NZD":"新西兰","OMR":"阿曼","PAB":"巴拿马","PEN":"秘鲁","PGK":"巴布亚新几内亚","PHP":"菲律宾","PKR":"巴基斯坦","PLN":"波兰","PYG":"巴拉圭","QAR":"卡塔尔","RON":"罗马尼亚","RSD":"塞尔维亚","RUB":"俄罗斯","RWF":"卢旺达","SAR":"沙特阿拉伯","SBD":"所罗门群岛","SCR":"塞舌尔","SDG":"苏丹","SEK":"瑞典","SGD":"新加坡","SHP":"圣赫勒拿","SLL":"塞拉利昂","SOS":"索马里","SRD":"苏里南","SSP":"南苏丹","STN":"圣多美和普林西比","SVC":"萨尔瓦多","SYP":"叙利亚","SZL":"斯威士兰","THB":"泰国","TJS":"塔吉克斯坦","TMT":"土库曼斯坦","TND":"突尼斯","TOP":"汤加","TRY":"土耳其","TTD":"特立尼达和多巴哥","TWD":"台湾","TZS":"坦桑尼亚","UAH":"乌克兰","UGX":"乌干达","USD":"美国","UYU":"乌拉圭","UZS":"乌兹别克斯坦","VES":"委内瑞拉","VND":"越南","VUV":"瓦努阿图","WST":"萨摩亚","XAF":"喀麦隆","XCD":"安提瓜和巴布达","XOF":"塞内加尔","XPF":"法属波利尼西亚","YER":"也门","ZAR":"南非","ZMW":"赞比亚","ZWL":"津巴布韦"},
  ko: {"AED":"아랍에미리트","AFN":"아프가니스탄","ALL":"알바니아","AMD":"아르메니아","ANG":"퀴라소","AOA":"앙골라","ARS":"아르헨티나","AUD":"오스트레일리아","AWG":"아루바","AZN":"아제르바이잔","BAM":"보스니아 헤르체고비나","BBD":"바베이도스","BDT":"방글라데시","BGN":"불가리아","BHD":"바레인","BIF":"부룬디","BMD":"버뮤다","BND":"브루나이","BOB":"볼리비아","BRL":"브라질","BSD":"바하마","BTN":"부탄","BWP":"보츠와나","BYN":"벨라루스","BZD":"벨리즈","CAD":"캐나다","CDF":"콩고-킨샤사","CHF":"스위스","CLP":"칠레","CNY":"중국","COP":"콜롬비아","CRC":"코스타리카","CUP":"쿠바","CVE":"카보베르데","CZK":"체코","DJF":"지부티","DKK":"덴마크","DOP":"도미니카 공화국","DZD":"알제리","EGP":"이집트","ERN":"에리트리아","ETB":"에티오피아","EUR":"유럽 연합","FJD":"피지","FKP":"포클랜드 제도","GBP":"영국","GEL":"조지아","GHS":"가나","GIP":"지브롤터","GMD":"감비아","GNF":"기니","GTQ":"과테말라","GYD":"가이아나","HKD":"홍콩(중국 특별행정구)","HNL":"온두라스","HRK":"크로아티아","HTG":"아이티","HUF":"헝가리","IDR":"인도네시아","ILS":"이스라엘","INR":"인도","IQD":"이라크","IRR":"이란","ISK":"아이슬란드","JMD":"자메이카","JOD":"요르단","JPY":"일본","KES":"케냐","KGS":"키르기스스탄","KHR":"캄보디아","KMF":"코모로","KRW":"대한민국","KWD":"쿠웨이트","KYD":"케이맨 제도","KZT":"카자흐스탄","LAK":"라오스","LBP":"레바논","LKR":"스리랑카","LRD":"라이베리아","LSL":"레소토","LYD":"리비아","MAD":"모로코","MDL":"몰도바","MGA":"마다가스카르","MKD":"북마케도니아","MMK":"미얀마","MNT":"몽골","MOP":"마카오(중국 특별행정구)","MRU":"모리타니","MUR":"모리셔스","MVR":"몰디브","MWK":"말라위","MXN":"멕시코","MYR":"말레이시아","MZN":"모잠비크","NAD":"나미비아","NGN":"나이지리아","NIO":"니카라과","NOK":"노르웨이","NPR":"네팔","NZD":"뉴질랜드","OMR":"오만","PAB":"파나마","PEN":"페루","PGK":"파푸아뉴기니","PHP":"필리핀","PKR":"파키스탄","PLN":"폴란드","PYG":"파라과이","QAR":"카타르","RON":"루마니아","RSD":"세르비아","RUB":"러시아","RWF":"르완다","SAR":"사우디아라비아","SBD":"솔로몬 제도","SCR":"세이셸","SDG":"수단","SEK":"스웨덴","SGD":"싱가포르","SHP":"세인트헬레나","SLL":"시에라리온","SOS":"소말리아","SRD":"수리남","SSP":"남수단","STN":"상투메 프린시페","SVC":"엘살바도르","SYP":"시리아","SZL":"에스와티니","THB":"태국","TJS":"타지키스탄","TMT":"투르크메니스탄","TND":"튀니지","TOP":"통가","TRY":"튀르키예","TTD":"트리니다드 토바고","TWD":"대만","TZS":"탄자니아","UAH":"우크라이나","UGX":"우간다","USD":"미국","UYU":"우루과이","UZS":"우즈베키스탄","VES":"베네수엘라","VND":"베트남","VUV":"바누아투","WST":"사모아","XAF":"카메룬","XCD":"앤티가 바부다","XOF":"세네갈","XPF":"프랑스령 폴리네시아","YER":"예멘","ZAR":"남아프리카","ZMW":"잠비아","ZWL":"짐바브웨"},
};

const SYMBOLS = {
  USD: "$", EUR: "€", GBP: "£", JPY: "¥", CNY: "¥", ILS: "₪", INR: "₹",
  KRW: "₩", RUB: "₽", TRY: "₺", VND: "₫", THB: "฿", PHP: "₱", NGN: "₦",
  UAH: "₴", BRL: "R$", CAD: "C$", AUD: "A$", NZD: "NZ$", HKD: "HK$",
  TWD: "NT$", SGD: "S$", MXN: "MX$", CHF: "CHF", PLN: "zł", CZK: "Kč",
  SEK: "kr", NOK: "kr", DKK: "kr", HUF: "Ft", ZAR: "R", AED: "د.إ",
  SAR: "﷼", EGP: "E£", PKR: "₨", LKR: "₨", NPR: "₨", IDR: "Rp",
  MYR: "RM", KZT: "₸", GEL: "₾", AZN: "₼", ARS: "$", CLP: "$", COP: "$"
};

const DETECT_SYMBOLS = [
  ["R$","BRL"], ["C$","CAD"], ["A$","AUD"], ["NZ$","NZD"], ["HK$","HKD"],
  ["NT$","TWD"], ["S$","SGD"], ["MX$","MXN"], ["E£","EGP"],
  ["₪","ILS"], ["₹","INR"], ["€","EUR"], ["£","GBP"], ["¥","JPY"],
  ["₩","KRW"], ["₽","RUB"], ["₺","TRY"], ["₫","VND"], ["฿","THB"],
  ["₱","PHP"], ["₦","NGN"], ["₴","UAH"], ["₸","KZT"], ["₾","GEL"],
  ["₼","AZN"], ["₨","PKR"], ["Rp","IDR"], ["RM","MYR"], ["zł","PLN"],
  ["Kč","CZK"], ["Ft","HUF"], ["$","USD"]
];

if (typeof module !== "undefined") module.exports = { CURRENCIES, SYMBOLS, DETECT_SYMBOLS, NAMES };

const WORDS = {
  dollar:"USD", dollars:"USD", usd:"USD", buck:"USD", bucks:"USD",
  euro:"EUR", euros:"EUR", eur:"EUR",
  pound:"GBP", pounds:"GBP", sterling:"GBP", quid:"GBP",
  yen:"JPY", yuan:"CNY", rmb:"CNY", won:"KRW",
  rupee:"INR", rupees:"INR", rs:"INR",
  shekel:"ILS", shekels:"ILS", sheqel:"ILS", nis:"ILS",
  ruble:"RUB", rubles:"RUB", rouble:"RUB", roubles:"RUB",
  peso:"MXN", pesos:"MXN", real:"BRL", reais:"BRL",
  lira:"TRY", franc:"CHF", francs:"CHF", rand:"ZAR",
  zloty:"PLN", krona:"SEK", krone:"NOK", forint:"HUF",
  baht:"THB", dong:"VND", ringgit:"MYR", rupiah:"IDR", peseta:"EUR",
  dirham:"AED", riyal:"SAR", rial:"SAR", dinar:"JOD", taka:"BDT",
  "שקל":"ILS", "שקלים":"ILS", "שח":"ILS", "ש״ח":"ILS", "ש\"ח":"ILS",
  "דולר":"USD", "דולרים":"USD", "יורו":"EUR", "אירו":"EUR",
  "פאונד":"GBP", "ליש״ט":"GBP", "ין":"JPY", "רופי":"INR", "רופיז":"INR",
  "יואן":"CNY", "רובל":"RUB", "פזו":"MXN", "לירה":"TRY"
};

if (typeof module !== "undefined") module.exports.WORDS = WORDS;

const UI = {
  en: { setTo:"SET TO", from:"CONVERT FROM", pick:"Select currency", pickBase:"Select base currency",
        search:"Search currencies...", favs:"SAVED", current:"CURRENT", noMatch:"NO MATCH",
        noData:"NO DATA", settings:"Settings", language:"Language", rowSize:"Price bar size",
        currencies:"Currencies", addCur:"Add currency", rate:"Rate source", refresh:"Refresh rates now",
        updated:"Updated", preview:"Preview", smaller:"Smaller", bigger:"Bigger", removeCur:"Remove", auto:"AUTO" , theme:"Theme", opacity:"Opacity", glass:"Glass", solid:"Solid", numFont:"Number font", justNow:"just now", minAgo:"{n} min ago", hrAgo:"{n} hr ago", dayAgo:"{n} days ago", tip1:"I built this on my own time and it is completely free.", tip2:"If you ever want to give something back, there is a way.", tipBtn:"Thanks", ext:"Extension", onWord:"On", offWord:"Off", copyHint:"Click to copy", copied:"Copied", guide:"Guide", gBack:"Back", gNext:"Next", gDone:"Got it", gStep:"Step", ratesBy:"Rates by", flagsBy:"Flags by", licenses:"Licenses", calc:"Convert", amount:"Amount", cFrom:"From", cTo:"To", swap:"Swap", gSkip:"Skip", swapWith:"Swap"},
  he: { setTo:"המרה ל", from:"המרה מ", pick:"בחר מטבע", pickBase:"בחר מטבע מקור",
        search:"חפש מטבע...", favs:"שמורים", current:"נוכחי", noMatch:"אין תוצאה",
        noData:"אין נתונים", settings:"הגדרות", language:"שפה", rowSize:"גודל שורת המחירים",
        currencies:"מטבעות", addCur:"הוסף מטבע", rate:"מקור השערים", refresh:"רענן שערים עכשיו",
        updated:"עודכן", preview:"תצוגה מקדימה", smaller:"קטן", bigger:"גדול", removeCur:"הסר", auto:"אוטומטי" , theme:"ערכת צבע", opacity:"שקיפות", glass:"זכוכית", solid:"מלא", numFont:"פונט המספרים", justNow:"ממש עכשיו", minAgo:"לפני {n} דקות", hrAgo:"לפני {n} שעות", dayAgo:"לפני {n} ימים", tip1:"בניתי את זה בזמן שלי, והוא חינמי לגמרי.", tip2:"אם בא לך להחזיר משהו, יש דרך.", tipBtn:"תודה", ext:"התוסף", onWord:"פעיל", offWord:"כבוי", copyHint:"לחץ להעתקה", copied:"הועתק", guide:"מדריך", gBack:"הקודם", gNext:"הבא", gDone:"הבנתי", gStep:"שלב", ratesBy:"שערים מאת", flagsBy:"דגלים מאת", licenses:"רישיונות", calc:"המרה", amount:"סכום", cFrom:"מ", cTo:"ל", swap:"החלף", gSkip:"דלג", swapWith:"החלף"},
  ru: { setTo:"В ВАЛЮТУ", from:"ИЗ ВАЛЮТЫ", pick:"Выберите валюту", pickBase:"Выберите базовую валюту",
        search:"Поиск валют...", favs:"СОХРАНЁННЫЕ", current:"ТЕКУЩАЯ", noMatch:"НЕТ СОВПАДЕНИЙ",
        noData:"НЕТ ДАННЫХ", settings:"Настройки", language:"Язык", rowSize:"Размер строки цен",
        currencies:"Валюты", addCur:"Добавить валюту", rate:"Источник курсов", refresh:"Обновить курсы",
        updated:"Обновлено", preview:"Предпросмотр", smaller:"Меньше", bigger:"Больше", removeCur:"Удалить", auto:"АВТО" , theme:"Тема", opacity:"Прозрачность", glass:"Стекло", solid:"Плотный", numFont:"Шрифт цифр", justNow:"только что", minAgo:"{n} мин назад", hrAgo:"{n} ч назад", dayAgo:"{n} дн назад", tip1:"Я сделал это в свободное время, и оно полностью бесплатно.", tip2:"Если захотите чем-то отблагодарить, такая возможность есть.", tipBtn:"Спасибо", ext:"Расширение", onWord:"Вкл", offWord:"Выкл", copyHint:"Нажмите, чтобы скопировать", copied:"Скопировано", guide:"Руководство", gBack:"Назад", gNext:"Далее", gDone:"Понятно", gStep:"Шаг", ratesBy:"Курсы от", flagsBy:"Флаги от", licenses:"Лицензии", calc:"Конвертер", amount:"Сумма", cFrom:"Из", cTo:"В", swap:"Поменять", gSkip:"Пропустить", swapWith:"Поменять"},
  es: { setTo:"CONVERTIR A", from:"CONVERTIR DE", pick:"Elegir moneda", pickBase:"Elegir moneda base",
        search:"Buscar monedas...", favs:"GUARDADOS", current:"ACTUAL", noMatch:"SIN RESULTADOS",
        noData:"SIN DATOS", settings:"Ajustes", language:"Idioma", rowSize:"Tamaño de la barra",
        currencies:"Monedas", addCur:"Añadir moneda", rate:"Fuente de tasas", refresh:"Actualizar tasas",
        updated:"Actualizado", preview:"Vista previa", smaller:"Menor", bigger:"Mayor", removeCur:"Quitar", auto:"AUTO" , theme:"Tema", opacity:"Opacidad", glass:"Cristal", solid:"Sólido", numFont:"Fuente de números", justNow:"ahora mismo", minAgo:"hace {n} min", hrAgo:"hace {n} h", dayAgo:"hace {n} días", tip1:"Hice esto en mi tiempo libre y es completamente gratis.", tip2:"Si alguna vez quieres devolver algo, hay una forma.", tipBtn:"Gracias", ext:"Extensión", onWord:"Activo", offWord:"Apagado", copyHint:"Haz clic para copiar", copied:"Copiado", guide:"Guía", gBack:"Atrás", gNext:"Siguiente", gDone:"Entendido", gStep:"Paso", ratesBy:"Tasas de", flagsBy:"Banderas de", licenses:"Licencias", calc:"Convertir", amount:"Importe", cFrom:"De", cTo:"A", swap:"Cambiar", gSkip:"Omitir", swapWith:"Intercambiar"},
  ja: { setTo:"変換先", from:"変換元", pick:"通貨を選択", pickBase:"基準通貨を選択",
        search:"通貨を検索...", favs:"保存済み", current:"現在", noMatch:"該当なし",
        noData:"データなし", settings:"設定", language:"言語", rowSize:"価格バーのサイズ",
        currencies:"通貨", addCur:"通貨を追加", rate:"レート提供元", refresh:"レートを更新",
        updated:"更新日時", preview:"プレビュー", smaller:"小", bigger:"大", removeCur:"削除", auto:"自動" , theme:"テーマ", opacity:"不透明度", glass:"ガラス", solid:"不透明", numFont:"数字のフォント", justNow:"たった今", minAgo:"{n}分前", hrAgo:"{n}時間前", dayAgo:"{n}日前", tip1:"自分の時間で作ったもので、完全に無料です。", tip2:"何かお返ししたくなったら、その方法があります。", tipBtn:"ありがとう", ext:"拡張機能", onWord:"オン", offWord:"オフ", copyHint:"クリックでコピー", copied:"コピーしました", guide:"ガイド", gBack:"戻る", gNext:"次へ", gDone:"わかりました", gStep:"ステップ", ratesBy:"レート提供", flagsBy:"国旗提供", licenses:"ライセンス", calc:"換算", amount:"金額", cFrom:"から", cTo:"へ", swap:"入れ替え", gSkip:"スキップ", swapWith:"入れ替え"},
  zh: { setTo:"转换为", from:"转换自", pick:"选择货币", pickBase:"选择基准货币",
        search:"搜索货币...", favs:"已保存", current:"当前", noMatch:"无匹配",
        noData:"无数据", settings:"设置", language:"语言", rowSize:"价格栏大小",
        currencies:"货币", addCur:"添加货币", rate:"汇率来源", refresh:"立即更新汇率",
        updated:"已更新", preview:"预览", smaller:"小", bigger:"大", removeCur:"移除", auto:"自动" , theme:"主题", opacity:"不透明度", glass:"玻璃", solid:"实心", numFont:"数字字体", justNow:"刚刚", minAgo:"{n}分钟前", hrAgo:"{n}小时前", dayAgo:"{n}天前", tip1:"这是我用自己的时间做的，完全免费。", tip2:"如果你想回馈一点什么，这里有个方式。", tipBtn:"谢谢", ext:"扩展程序", onWord:"开", offWord:"关", copyHint:"点击复制", copied:"已复制", guide:"使用指南", gBack:"上一步", gNext:"下一步", gDone:"知道了", gStep:"步骤", ratesBy:"汇率来自", flagsBy:"国旗来自", licenses:"许可证", calc:"换算", amount:"金额", cFrom:"从", cTo:"到", swap:"交换", gSkip:"跳过", swapWith:"交换"},
  ko: { setTo:"변환 대상", from:"변환 원본", pick:"통화 선택", pickBase:"기준 통화 선택",
        search:"통화 검색...", favs:"저장됨", current:"현재", noMatch:"검색 결과 없음",
        noData:"데이터 없음", settings:"설정", language:"언어", rowSize:"가격 표시줄 크기",
        currencies:"통화", addCur:"통화 추가", rate:"환율 출처", refresh:"환율 새로고침",
        updated:"업데이트됨", preview:"미리보기", smaller:"작게", bigger:"크게", removeCur:"제거", auto:"자동" , theme:"테마", opacity:"불투명도", glass:"유리", solid:"불투명", numFont:"숫자 글꼴", justNow:"방금", minAgo:"{n}분 전", hrAgo:"{n}시간 전", dayAgo:"{n}일 전", tip1:"제 시간을 들여 만들었고, 완전히 무료입니다.", tip2:"돌려주고 싶은 마음이 든다면, 방법이 있습니다.", tipBtn:"감사합니다", ext:"확장 프로그램", onWord:"켜기", offWord:"끄기", copyHint:"클릭하여 복사", copied:"복사됨", guide:"사용 안내", gBack:"이전", gNext:"다음", gDone:"확인", gStep:"단계", ratesBy:"환율 제공", flagsBy:"국기 제공", licenses:"라이선스", calc:"변환", amount:"금액", cFrom:"에서", cTo:"으로", swap:"교체", gSkip:"건너뛰기", swapWith:"교체"}
};

const LANGS = [["en","English"],["he","עברית"],["ru","Русский"],["es","Español"],
               ["ja","日本語"],["zh","中文"],["ko","한국어"]];

const RTL = { he: true };

if (typeof module !== "undefined") { module.exports.UI = UI; module.exports.LANGS = LANGS; module.exports.RTL = RTL; }

const THEMES = {
  blue: { pwr: ["#ff2f8e","#c94ae6","#6d5bea","#2ec2ff"],
    label: "Darkmode",
    arrow: "#8fa6d8",
    swatch: "linear-gradient(90deg,#06060e 0%,#14275e 10.6%,#2149ad 21.1%,#2f6bff 32%,#2d8ffc 37.9%,#2ab4f8 43.9%,#28d9f5 50%,#2ab5f8 55.9%,#2d90fc 61.9%,#2f6bff 68%,#214aaf 78.6%,#142860 89.1%,#06060e 100%)",
    edge: "linear-gradient(90deg,#2f6bff 0%,#2d8ffc 9.2%,#2ab4f8 18.5%,#28d9f5 28%,#51b0f8 39.2%,#7a86fc 50.4%,#a45cff 62%,#c25dec 74.5%,#e05ed8 87.1%,#ff5fc4 100%)",
    barBg: "#06060e", barBorder: "#1d2748", slotLine: "#16203c",
    slotBg: "linear-gradient(180deg,#0b0c1a 0%,#090a16 33%,#080812 66%,#06060e 100%)",
    srcBg: "linear-gradient(180deg,#140a20 0%,#11081b 33%,#0d0717 66%,#0a0512 100%)",
    srcLine: "#3a2352", srcText: "#e9b6ff", srcLabel: "#b07cd8",
    label_: "#6f7ba6", value: "#eaf2ff", muted: "#4a5479",
    accent: "#28d9f5", accent2: "#2f6bff", dropBg: "#05050c", dropBorder: "#26315a",
    rowHover: "#101533", rowCur: "#0d1330", chipBg: "#0e1226", chipBorder: "#232d52",
    star: "#ffc94d", xHover: "#ff6bb5",
    px: ["#90caf9","#64b5f6","#42a5f5","#2196f3","#1e88e5","#1976d2","#1565c0","#0d47a1","#0a30f8","#081c90"],
    flash: ["rgba(33,150,243,.22)","rgba(144,202,249,.8)","rgba(21,101,192,.12)","rgba(100,181,246,.4)"]
  },
  red: { pwr: ["#ff2f6e","#ff5566","#c9385f","#7a2b6b"],
    label: "Red",
    arrow: "#d99aa4",
    edge: "linear-gradient(90deg,#ff2d3f 0%,#ff413e 9.9%,#ff563e 19.8%,#ff6b3d 30%,#ff574e 41.5%,#ff425e 53.1%,#ff2d6f 65%,#ec2358 76.5%,#d81a41 88.1%,#c4102a 100%)",
    barBg: "#0d0406", barBorder: "#4a1420", slotLine: "#33101a",
    slotBg: "linear-gradient(180deg,#1a0709 0%,#160608 33%,#110507 66%,#0d0406 100%)",
    srcBg: "linear-gradient(180deg,#24070c 0%,#1e060a 33%,#180408 66%,#120306 100%)",
    srcLine: "#6b1d2c", srcText: "#ffb3bf", srcLabel: "#d8707f",
    label_: "#a6737b", value: "#ffeaec", muted: "#79484f",
    accent: "#ff5566", accent2: "#c4102a", dropBg: "#0c0305", dropBorder: "#5a1a26",
    rowHover: "#25090e", rowCur: "#2a0a11", chipBg: "#1c0609", chipBorder: "#4a1420",
    star: "#ffc94d", xHover: "#ff8a5c",
    px: ["#ffcdd2","#ef9a9a","#e57373","#ef5350","#f44336","#e53935","#d32f2f","#c62828","#b71c1c","#7f0f14"],
    flash: ["rgba(244,67,54,.22)","rgba(255,205,210,.8)","rgba(183,28,28,.12)","rgba(239,154,154,.4)"]
  },
  green: { pwr: ["#00e5a0","#1de9b6","#26c6da","#2ec2ff"],
    label: "Green",
    arrow: "#8dc7ac",
    edge: "linear-gradient(90deg,#00e676 0%,#0ae78b 9.9%,#13e8a0 19.8%,#1de9b6 30%,#34e582 41.5%,#4ce14d 53.1%,#64dd17 65%,#43c138 76.5%,#22a659 88.1%,#00897b 100%)",
    barBg: "#040d08 ", barBorder: "#14402a", slotLine: "#10301f",
    slotBg: "linear-gradient(180deg,#071a0f 0%,#06160d 33%,#05110a 66%,#040d08 100%)",
    srcBg: "linear-gradient(180deg,#07231a 0%,#061d15 33%,#041811 66%,#03120c 100%)",
    srcLine: "#1d6b4e", srcText: "#b3ffd9", srcLabel: "#70d8a6",
    label_: "#73a68b", value: "#eaffef", muted: "#487961",
    accent: "#1de9b6", accent2: "#00897b", dropBg: "#030c07", dropBorder: "#1a5a3a",
    rowHover: "#0a2517", rowCur: "#0b2a1a", chipBg: "#061c11", chipBorder: "#14402a",
    star: "#ffc94d", xHover: "#5cffb0",
    px: ["#c8e6c9","#a5d6a7","#81c784","#66bb6a","#4caf50","#43a047","#388e3c","#2e7d32","#1b5e20","#0d3d14"],
    flash: ["rgba(76,175,80,.22)","rgba(200,230,201,.8)","rgba(27,94,32,.12)","rgba(165,214,167,.4)"]
  },
  mono: { pwr: ["#ffffff","#d4d4d4","#9e9e9e","#6b6b6b"],
    label: "Black & White",
    arrow: "#c8c8c8",
    edge: "linear-gradient(90deg,#ffffff 0%,#dfdfdf 9.9%,#bfbfbf 19.8%,#9e9e9e 30%,#b4b4b4 41.5%,#cacaca 53.1%,#e0e0e0 65%,#b6b6b6 76.5%,#8c8c8c 88.1%,#616161 100%)",
    barBg: "#080808", barBorder: "#3a3a3a", slotLine: "#242424",
    slotBg: "linear-gradient(180deg,#141414 0%,#101010 33%,#0c0c0c 66%,#080808 100%)",
    srcBg: "linear-gradient(180deg,#ffffff 0%,#f7f7f7 33%,#eeeeee 66%,#e6e6e6 100%)",
    srcLine: "#ffffff", srcText: "#0a0a0a", srcLabel: "#5a5a5a",
    label_: "#8a8a8a", value: "#ffffff", muted: "#5c5c5c",
    accent: "#ffffff", accent2: "#9e9e9e", dropBg: "#0a0a0a", dropBorder: "#454545",
    rowHover: "#1c1c1c", rowCur: "#202020", chipBg: "#161616", chipBorder: "#3a3a3a",
    star: "#ffffff", xHover: "#ffffff",
    px: ["#ffffff","#f0f0f0","#d6d6d6","#bdbdbd","#9e9e9e","#7a7a7a","#5c5c5c","#3d3d3d","#242424","#111111"],
    flash: ["rgba(255,255,255,.20)","rgba(255,255,255,.85)","rgba(255,255,255,.08)","rgba(255,255,255,.35)"]
  }
};

const THEME_LIST = [["blue","Darkmode"],["red","Red"],["green","Green"],["mono","Black & White"]];

if (typeof module !== "undefined") { module.exports.THEMES = THEMES; module.exports.THEME_LIST = THEME_LIST; }

const NUM_FONTS = [
  ["inter",     "Inter",          "inter",          17],
  ["noto",      "Noto Sans",      "noto-sans",      17],
  ["plex",      "IBM Plex Mono",  "ibm-plex-mono",  15],
  ["roboto",    "Roboto",         "roboto",         14],
  ["display",   "Display",        null,              3]
];

const LIGHT = { pwr: ["#e0157f","#9333ea","#4f46e5","#0284c7"],
  label: "Lightmode",
    arrow: "#5c6b86",
  swatch: "linear-gradient(90deg,#ffffff 0%,#bed6fc 10.6%,#7eacf9 21.1%,#3b82f6 32%,#3478f2 37.9%,#2c6eef 43.9%,#2563eb 50%,#2c6def 55.9%,#3477f2 61.9%,#3b82f6 68%,#7cabf9 78.6%,#bcd4fc 89.1%,#ffffff 100%)",
  edge: "linear-gradient(90deg,#3b82f6 0%,#2a93eb 9.9%,#18a4e0 19.8%,#06b6d4 30%,#3298df 41.5%,#5e7bea 53.1%,#8b5cf6 65%,#ab55d7 76.5%,#cb4fb9 88.1%,#ec4899 100%)",
  barBg: "#f4f6fb", barBorder: "#c9d2e4", slotLine: "#dde4f0",
  slotBg: "linear-gradient(180deg,#ffffff 0%,#fbfcfe 33%,#f8f9fc 66%,#f4f6fb 100%)",
  srcBg: "linear-gradient(180deg,#f3edff 0%,#f0e9fe 33%,#ece4fc 66%,#e9e0fb 100%)",
  srcLine: "#c9b6ea", srcText: "#5b3a94", srcLabel: "#7c5bb5",
  label_: "#63708c", value: "#1b2436", muted: "#93a0b8",
  accent: "#2563eb", accent2: "#7c93c7", dropBg: "#ffffff", dropBorder: "#cdd7e8",
  rowHover: "#eef2fa", rowCur: "#e6edfd", chipBg: "#eef2fa", chipBorder: "#cdd7e8",
  star: "#e0a416", xHover: "#d94a7a",
  px: ["#dbeafe","#bfdbfe","#93c5fd","#60a5fa","#3b82f6","#2563eb","#1d4ed8","#1e40af","#1e3a8a","#172554"],
  flash: ["rgba(37,99,235,.16)","rgba(37,99,235,.55)","rgba(37,99,235,.08)","rgba(37,99,235,.25)"]
};
THEMES.light = LIGHT;
THEME_LIST.splice(1, 0, ["light", "Lightmode"]);

if (typeof module !== "undefined") { module.exports.NUM_FONTS = NUM_FONTS; }

const TOUR = {
  en: [["power","The master switch","Turns the extension off on every site at once. Your settings are kept for when you switch it back on."],["langPick","Language","Seven languages. This changes the menus and the country names in the currency list."],["fontPick","Number font","Changes how the converted amounts look. The count next to each font is how many currency symbols it can draw."],["previewWrap","This is the bar","Select any price on any page and this appears above it. Click a number to copy it, use the arrows to swap two currencies."],["size","Bar size","Sets how large the bar is on websites. The preview above updates as you drag, so you can see the result before you leave this page."],["opacity","Transparency","How solid the bar looks over the page. Below 20% it fades further when you hover it, so you can read what is underneath."],["themes","Colour themes","Five of them. The choice applies to the bar on websites and to this page."],["srcPick","Convert from","The currency the extension assumes when the page shows a bare number. If the page has a symbol, it uses that instead. Add and remove the other currencies straight from the bar."],["h-calc","The converter","Type any amount to convert it without needing a page. Useful when there is nothing to select."],["refresh","Rates","Updated automatically every few hours. This button forces a refresh, and the line below shows when it last happened."]],
  he: [["power","המתג הראשי","מכבה את התוסף בכל האתרים בבת אחת. ההגדרות נשמרות לפעם הבאה שתדליק."],["langPick","שפה","שבע שפות. זה משנה את התפריטים וגם את שמות המדינות ברשימת המטבעות."],["fontPick","פונט המספרים","קובע איך הסכומים המומרים נראים. המספר ליד כל פונט הוא כמה סמלי מטבע הוא יודע להציג."],["previewWrap","זה הפס","סמן מחיר בכל אתר והוא יופיע מעליו. לחיצה על מספר מעתיקה אותו, והחצים מחליפים בין שני מטבעות."],["size","גודל הפס","קובע כמה גדול הפס באתרים. התצוגה למעלה מתעדכנת תוך כדי גרירה, כדי שתראה את התוצאה לפני שאתה יוצא מהדף."],["opacity","שקיפות","כמה הפס אטום מעל הדף. מתחת ל‑20 אחוז הוא נעשה שקוף עוד יותר בריחוף, כדי שתוכל לקרוא מה שמתחתיו."],["themes","ערכות צבע","חמש ערכות. הבחירה חלה גם על הפס באתרים וגם על הדף הזה."],["srcPick","ממה ממירים","המטבע שהתוסף מניח כשבאתר מופיע מספר בלבד. אם יש סימן מטבע, הוא מזוהה לבד. את שאר המטבעות מוסיפים ומסירים ישירות מהפס."],["h-calc","הממיר","אפשר להקליד כל סכום ולהמיר אותו בלי אתר. שימושי כשאין מה לסמן."],["refresh","שערים","מתעדכנים לבד כל כמה שעות. הכפתור מרענן מיד, והשורה מתחתיו מראה מתי זה קרה לאחרונה."]],
  ru: [["power","Главный переключатель","Отключает расширение сразу на всех сайтах. Настройки сохраняются."],["langPick","Язык","Семь языков. Меняются меню и названия стран в списке валют."],["fontPick","Шрифт цифр","Задаёт вид пересчитанных сумм. Число рядом со шрифтом - сколько символов валют он умеет рисовать."],["previewWrap","Это и есть панель","Выделите цену на любой странице, и панель появится над ней. Клик по числу копирует его."],["size","Размер панели","Задаёт размер панели на сайтах. Предпросмотр выше обновляется прямо при перетаскивании."],["opacity","Прозрачность","Насколько панель непрозрачна. Ниже 20% она дополнительно тускнеет при наведении, чтобы было видно, что под ней."],["themes","Цветовые темы","Пять тем. Выбор применяется и к панели на сайтах, и к этой странице."],["srcPick","Исходная валюта","Используется, когда на странице стоит просто число. Если есть символ валюты, он распознаётся сам. Остальные валюты добавляются прямо на панели."],["h-calc","Конвертер","Введите любую сумму без всякой страницы. Удобно, когда нечего выделять."],["refresh","Курсы","Обновляются сами раз в несколько часов. Кнопка обновляет сразу."]],
  es: [["power","El interruptor principal","Desactiva la extensión en todos los sitios a la vez. Tus ajustes se conservan."],["langPick","Idioma","Siete idiomas. Cambia los menús y los nombres de países en la lista de monedas."],["fontPick","Fuente de los números","Define el aspecto de los importes. El número junto a cada fuente indica cuántos símbolos puede dibujar."],["previewWrap","Esta es la barra","Selecciona un precio en cualquier página y aparece encima. Haz clic en un número para copiarlo."],["size","Tamaño de la barra","Define su tamaño en las webs. La vista previa se actualiza mientras arrastras."],["opacity","Transparencia","Cuán sólida se ve sobre la página. Por debajo del 20% se atenúa más al pasar el ratón para leer lo que hay debajo."],["themes","Temas de color","Cinco temas. Se aplican a la barra en las webs y a esta página."],["srcPick","Moneda de origen","La que se usa cuando la página muestra solo un número. Si hay símbolo, se detecta solo. Las demás se añaden desde la barra."],["h-calc","El conversor","Escribe cualquier importe sin necesidad de una página."],["refresh","Tasas","Se actualizan solas cada pocas horas. Este botón fuerza una actualización."]],
  ja: [["power","メインスイッチ","すべてのサイトで拡張機能を一度に無効化します。設定はそのまま保持されます。"],["langPick","言語","7言語に対応。メニューと通貨一覧の国名が切り替わります。"],["fontPick","数字のフォント","換算後の金額の見た目を決めます。横の数字は表示できる通貨記号の数です。"],["previewWrap","これがバーです","任意のページで価格を選択すると、その上に表示されます。数字をクリックするとコピーされます。"],["size","バーの大きさ","サイト上での表示サイズを決めます。ドラッグ中に上のプレビューが更新されます。"],["opacity","不透明度","ページの上でどれだけはっきり見えるか。20%未満ではカーソルを重ねるとさらに薄くなり、下の内容が読めます。"],["themes","配色テーマ","5種類。サイト上のバーとこのページの両方に適用されます。"],["srcPick","換算元","ページに数字だけがある場合に使われる通貨です。記号があれば自動で判定します。他の通貨はバーから追加できます。"],["h-calc","換算ツール","ページがなくても金額を入力して換算できます。"],["refresh","レート","数時間ごとに自動更新されます。このボタンですぐに更新できます。"]],
  zh: [["power","主开关","一次性在所有网站上停用扩展。你的设置会被保留。"],["langPick","语言","支持七种语言，会同时改变菜单和货币列表中的国家名。"],["fontPick","数字字体","决定换算金额的外观。字体旁的数字表示它能显示多少种货币符号。"],["previewWrap","这就是那个栏","在任何网页选中价格，它就会出现在上方。点击数字即可复制。"],["size","栏的大小","决定它在网页上的显示大小。拖动时上方的预览会实时更新。"],["opacity","透明度","它盖在网页上的实心程度。低于20%时，鼠标悬停会进一步淡化，方便看清下方内容。"],["themes","配色主题","共五种。同时应用于网页上的栏和此页面。"],["srcPick","源货币","当网页只显示数字时使用的货币。如果有货币符号则自动识别。其他货币可直接在栏中添加。"],["h-calc","换算器","无需网页也能输入任意金额进行换算。"],["refresh","汇率","每隔几小时自动更新。此按钮可立即刷新。"]],
  ko: [["power","메인 스위치","모든 사이트에서 확장 프로그램을 한 번에 끕니다. 설정은 그대로 유지됩니다."],["langPick","언어","7개 언어를 지원하며 메뉴와 통화 목록의 국가명이 함께 바뀝니다."],["fontPick","숫자 글꼴","환산 금액의 모양을 정합니다. 옆의 숫자는 표시 가능한 통화 기호 수입니다."],["previewWrap","이것이 바입니다","어느 페이지에서든 가격을 선택하면 그 위에 나타납니다. 숫자를 클릭하면 복사됩니다."],["size","바 크기","웹사이트에서의 표시 크기를 정합니다. 드래그하는 동안 위의 미리보기가 갱신됩니다."],["opacity","불투명도","페이지 위에서 얼마나 진하게 보이는지 정합니다. 20% 미만에서는 커서를 올리면 더 흐려져 아래 내용을 읽을 수 있습니다."],["themes","색상 테마","다섯 가지. 웹사이트의 바와 이 페이지에 모두 적용됩니다."],["srcPick","원본 통화","페이지에 숫자만 있을 때 사용하는 통화입니다. 기호가 있으면 자동 인식합니다. 다른 통화는 바에서 추가합니다."],["h-calc","변환기","페이지 없이도 원하는 금액을 입력해 변환할 수 있습니다."],["refresh","환율","몇 시간마다 자동 갱신됩니다. 이 버튼으로 즉시 새로고침할 수 있습니다."]],
};

if (typeof module !== "undefined") { module.exports.TOUR = TOUR; }
